# Starship for LINUX & macOS

# Inserts a blank line between shell prompts
add_newline = true

# Change command timeout from 500 to 1000 ms
command_timeout = 1000

format = """\
[â•­â•´](238)${custom.kali}${custom.arch}${custom.debian}${custom.raspbian}${custom.ubuntu}${custom.elementary}${custom.fedora}${custom.coreos}${custom.gentoo}${custom.mageia}${custom.centos}${custom.opensuse}${custom.sabayon}${custom.slackware}${custom.linuxmint}${custom.alpine}${custom.nixos}${custom.rhel}${custom.manjaro}${custom.macos}${custom.linux}\
$username$hostname$sudo$directory$git_branch$git_status$shell$cmd_duration
[â•°â”€](238)$character"""

# Change the default prompt characters
[character]
success_symbol = "[ï•“](238)"
error_symbol = "[ï•“](238)"

[hostname]
ssh_only = false
format = "on [$hostname](bold blue) "
trim_at = ".skynet.systems"
disabled = false

[username]
style_user = "white bold"
style_root = "red bold"
format = "[$user]($style) "
disabled = false
show_always = true

[cmd_duration]
min_time = 500
format = "took [$duration](bold yellow)"
show_milliseconds = false

[directory]
truncation_length = 100
truncate_to_repo = false
truncation_symbol = "â€¦/"
home_symbol = "ï´¤ ~"
read_only_style = "197"
read_only = " ï€£ "
format = "at [$path]($style)[$read_only]($read_only_style) "

[shell]
powershell_indicator = "via ï²µ"
unknown_indicator = "mystery shell"
style = "cyan bold"
disabled = false
zsh_indicator = ""

[git_branch]
symbol = "ï¡ "
format = "on [$symbol$branch]($style) "
truncation_length = 10
truncation_symbol = "â€¦/"
style = "bold green"

[git_status]
format = '[\($all_status$ahead_behind\)]($style) '
style = "bold green"
conflicted = "ğŸ³"
up_to_date = " ï† "
untracked = " ï”© "
ahead = "â‡¡${count}"
diverged = "â‡•â‡¡${ahead_count}â‡£${behind_count}"
behind = "â‡£${count}"
stashed = "ï£– "
modified = "ï„ "
staged = '[++\($count\)](green)'
renamed = "ïª¶ "
deleted = "ï€” "

[python]
symbol = "ï Ÿ "
python_binary = "python3"

[custom.docker]
description = "Shows the docker symbol if the current directory has Dockerfile or docker-compose.{yml,yaml} files"
symbol = "ïŒˆ'"
style = "bright-blue bold"
files = ["Dockerfile", "docker-compose.yml", "docker-compose.yaml"]
when = """ command -v docker &> /dev/null; exit (echo $?); """

########################### Linux & macOS CUSTOMIZATION

[custom.macos]
when = """ test "$STARSHIP_OS" "==" "macos" """
symbol = 'ï”´ '
style = "244 bold"
os = "macos"

[custom.kali]
when = """ test "$STARSHIP_OS" "==" "kali" """
symbol = 'ï´£ '
style = "253 bold"
os = "linux"

[custom.arch]
when = """ test "$STARSHIP_OS" "==" "arch" """
symbol = 'ïŒƒ '
style = "021 bold"
os = "linux"

[custom.debian]
when = """ test "$STARSHIP_OS" "==" "debian" """
symbol = 'ïŒ† '
style = "125 bold"
os = "linux"

[custom.raspbian]
when = """ test "$STARSHIP_OS" "==" "raspbian" """
symbol = 'ïŒ• '
style = "125 bold"
os = "linux"

[custom.elementary]
when = """ test "$STARSHIP_OS" "==" "elementary" """
symbol = 'ïŒ‰  '
style = "033 bold"
os = "linux"

[custom.fedora]
when = """ test "$STARSHIP_OS" "==" "fedora" """
symbol = 'ïŒŠ  '
style = "019 bold"
os = "linux"

[custom.coreos]
when = """ test "$STARSHIP_OS" "==" "coreos" """
symbol = 'ïŒ…  '
style = "033 bold"
os = "linux"

[custom.gentoo]
when = """ test "$STARSHIP_OS" "==" "gentoo" """
symbol = 'ïŒ  '
style = "105 bold"
os = "linux"

[custom.mageia]
when = """ test "$STARSHIP_OS" "==" "mageia" """
symbol = 'ïŒ  '
style = "025 bold"
os = "linux"

[custom.centos]
when = """ test "$STARSHIP_OS" "==" "centos" """
symbol = 'ïŒ„  '
style = "090 bold"

[custom.opensuse]
when = """ test "$STARSHIP_OS" "==" "opensuse" """
symbol = 'ïŒ”  '
style = "070 bold"
os = "linux"

[custom.sabayon]
when = """ test "$STARSHIP_OS" "==" "sabayon" """
symbol = 'ïŒ—  '
style = "251 bold"
os = "linux"

[custom.slackware]
when = """ test "$STARSHIP_OS" "==" "slackware" """
symbol = 'ïŒ˜  '
style = "105 bold"
os = "linux"

[custom.linuxmint]
when = """ test "$STARSHIP_OS" "==" "linuxmint" """
symbol = 'ïŒ  '
style = "#69b53e bold"
os = "linux"

[custom.alpine]
when = """ test "$STARSHIP_OS" "==" "alpine" """
symbol = 'ïŒ€  '
style = "#0e567b bold"
os = "linux"

[custom.nixos]
when = """ test "$STARSHIP_OS" "==" "nixos" """
symbol = 'ïŒ“  '
style = "#7bb4dd bold"
os = "linux"

[custom.manjaro]
when = """ test "$STARSHIP_OS" "==" "manjaro" """
symbol = 'ïŒ’  '
style = "#34b959 bold"
os = "linux"

[custom.rhel]
when = """ test "$STARSHIP_OS" "==" "rhel" """
symbol = 'ïŒ–  '
style = "#e63129 bold"
os = "linux"

[custom.ubuntu]
when = """ test "$STARSHIP_OS" "==" "ubuntu" """
symbol = 'ïŒœ  '
style = "#de5824 bold"
os = "linux"

[custom.linux]
when = """ test "$STARSHIP_OS" "==" "linux" """
symbol = 'ï…¼ '
style = "003 bold"
os = "linux"

